import React, { useState } from 'react';
import { Button } from '../components/common/Button';
import { Badge } from '../components/common/Badge';
import { Card } from '../components/common/Card';
import { CommitmentCard } from '../components/intelligence/CommitmentCard';
import { HistoricalContextCard } from '../components/intelligence/HistoricalContextCard';
import { useMeeting } from '../context/MeetingContext';
import {
  Printer,
  Download,
  Share2,
  CheckCircle2,
  Clock,
  Users,
  ShieldCheck,
  AlertTriangle,
  FileCheck2,
  Sparkles,
  ArrowRight,
  Quote,
  Target
} from 'lucide-react';

export const ReportPage = ({ onNavigate, onOpenEvidence, onOpenContradiction }) => {
  const { activeMeeting, actions } = useMeeting();
  const [copiedLink, setCopiedLink] = useState(false);

  const reportData = {
    title: activeMeeting?.title || "Q3 Stripe Billing & Latency Architecture Sync",
    client: activeMeeting?.client || "FinEdge Technologies",
    organization: activeMeeting?.organization || "Core Platform Team",
    date: activeMeeting?.date || "Sept 18, 2026",
    duration: "42 min",
    executiveSummary: "Executive alignment session. Addressed webhook retry contention under peak concurrency. Reached consensus to migrate to PostgreSQL 16 read replicas with connection pooling. Raj Patel committed to refactoring the payment API by Friday with staging deployment, and production sign-off scheduled for Monday after automated soak tests. Elena Rostova committed to delivering the signed SOC2 Type II audit package directly to the client by tomorrow.",
    topics: [
      { title: "Webhook Idempotency & Latency Contention", summary: "Diagnosed lock contention on connection poolers during concurrent retry bursts." },
      { title: "Database Read Replicas & Connection Pooling", summary: "Consensus to provision PostgreSQL 16 read replicas with Supabase pooled endpoints." },
      { title: "SOC2 Compliance Documentation", summary: "Parsed security audit trails for FinEdge's compliance and legal review." }
    ],
    decisions: [
      {
        decision: "Adopt PostgreSQL 16 Read Replicas with Supabase Connection Pooler",
        context: "Eliminates webhook connection starvation during concurrent retry bursts",
        evidence: "Alex Rivera (04:30): 'Decision agreed: we will use PostgreSQL 16 read replicas...'"
      },
      {
        decision: "Standardize on Redis Distributed Locks for Idempotency",
        context: "Ensures single execution of charging transactions across microservices",
        evidence: "Raj Patel (02:05): 'Refactoring Redis distributed lock and verifying end-to-end sandbox.'"
      }
    ],
    commitments: actions,
    customerRequirements: [
      { requirement: "Enterprise pilot begins October 1st; zero downtime tolerance", customer: "Sarah Chen (FinEdge)" },
      { requirement: "Signed SOC2 Type II audit report for enterprise compliance", customer: "Sarah Chen (FinEdge)" }
    ],
    customerConcerns: [
      { concern: "Delaying 4 major pilot accounts if payment API refactor slips past next week", level: "High" }
    ],
    contradictions: [
      {
        topic: "Production Deployment Timeline Revision",
        historicalStatement: "Raj Patel (Sept 12 sync): 'We will push full release to production on Friday, Sept 19.'",
        currentStatement: "Raj Patel (Today): 'Staging deployment on Friday, production sign-off moved to Monday morning.'",
        differenceSummary: "Target adjusted +3 days to allow continuous weekend load simulation.",
        badge: "Deadline Changed"
      }
    ],
    unresolved: [
      {
        task: "Setup Datadog APM Latency & p99 Dashboard",
        owner: "Needs Clarification",
        deadline: "Not specified",
        reason: "Alex asked who would configure Datadog, but no attendee accepted ownership before adjournment."
      }
    ]
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadMarkdown = () => {
    const mdContent = `# ${reportData.title}
**Client:** ${reportData.client} | **Date:** ${reportData.date} | **Duration:** ${reportData.duration}

## Executive Summary
${reportData.executiveSummary}

## Decisions Made
${reportData.decisions.map(d => `- **${d.decision}**\n  *Context:* ${d.context}\n  *Evidence:* ${d.evidence}`).join('\n\n')}

## Accountable Commitments
${reportData.commitments.map(c => `- **Task:** ${c.task}\n  - Owner: ${c.owner}\n  - Deadline: ${c.deadline}\n  - Status: ${c.status}`).join('\n\n')}

## Customer Requirements & Concerns
${reportData.customerRequirements.map(r => `- ${r.requirement} (${r.customer})`).join('\n')}

---
*Generated by G13 AI Meeting-to-Action Intelligence Agent*
`;
    const blob = new Blob([mdContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `G13_Report_${reportData.client.replace(/\s+/g, '_')}.md`;
    a.click();
  };

  const handleShare = () => {
    navigator.clipboard.writeText(window.location.href);
    setCopiedLink(true);
    setTimeout(() => setCopiedLink(false), 2000);
  };

  return (
    <div className="min-h-screen bg-[#080B16] text-white p-4 sm:p-8 max-w-6xl mx-auto space-y-8">
      {/* Top Action Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-6 border-b border-white/8 no-print">
        <div>
          <div className="flex items-center gap-2">
            <Badge variant="emerald" dot size="sm">
              VERIFIED FINAL REPORT
            </Badge>
            <span className="text-xs text-slate-400 font-mono">
              Meeting ID: {activeMeeting?.code || "G13-X7K92"}
            </span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-white font-display mt-1">
            {reportData.title}
          </h1>
          <p className="text-xs text-slate-400">
            {reportData.client} • {reportData.organization} • {reportData.date}
          </p>
        </div>

        <div className="flex items-center gap-2.5 flex-wrap">
          <Button
            variant="outline"
            size="sm"
            icon={Printer}
            onClick={handlePrint}
          >
            Print / PDF
          </Button>

          <Button
            variant="outline"
            size="sm"
            icon={Download}
            onClick={handleDownloadMarkdown}
          >
            Export Markdown
          </Button>

          <Button
            variant="outline"
            size="sm"
            icon={Share2}
            onClick={handleShare}
          >
            {copiedLink ? "Link Copied!" : "Share Link"}
          </Button>

          <Button
            variant="primary"
            size="sm"
            icon={Target}
            onClick={() => onNavigate('actions')}
            className="shadow-glow-sm"
          >
            Open Action Tracker
          </Button>
        </div>
      </div>

      {/* EXECUTIVE SUMMARY */}
      <div className="p-6 sm:p-8 rounded-3xl glass-panel-elevated border border-primary/25 space-y-4 shadow-xl">
        <div className="flex items-center justify-between">
          <span className="text-xs font-mono text-ai uppercase tracking-wider font-bold">
            Executive Brief
          </span>
          <span className="text-xs font-mono text-slate-400">
            Confidence: 96% Grounded
          </span>
        </div>

        <p className="text-sm sm:text-base text-slate-200 leading-relaxed font-light">
          {reportData.executiveSummary}
        </p>

        <div className="flex items-center gap-6 pt-4 border-t border-white/8 text-xs text-slate-400 flex-wrap">
          <span className="flex items-center gap-1.5">
            <Clock className="w-4 h-4 text-ai" /> {reportData.duration} duration
          </span>
          <span className="flex items-center gap-1.5">
            <Users className="w-4 h-4 text-slate-300" /> 5 Attendees Diarized
          </span>
          <span className="flex items-center gap-1.5 text-emerald-400 font-semibold">
            <CheckCircle2 className="w-4 h-4" /> {reportData.commitments.length} Commitments Validated
          </span>
        </div>
      </div>

      {/* SECTION: VERIFIED COMMITMENTS & ACTION ITEMS */}
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <h2 className="text-lg font-bold text-white font-display">
              Accountable Commitments & Action Items
            </h2>
            <Badge variant="emerald" size="xs">
              Evidence Grounded
            </Badge>
          </div>
          <span className="text-xs text-slate-400">
            {reportData.commitments.length} items logged
          </span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {reportData.commitments.map((item, idx) => (
            <CommitmentCard
              key={item.id || idx}
              item={item}
              onViewEvidence={onOpenEvidence}
              onViewContradiction={onOpenContradiction}
            />
          ))}
        </div>
      </div>

      {/* SECTION: CONTRADICTIONS & REVISIONS (RAG MEMORY) */}
      {reportData.contradictions.length > 0 && (
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <h2 className="text-lg font-bold text-white font-display">
                Cross-Meeting Contradictions & Revisions
              </h2>
              <Badge variant="amber" size="xs">
                RAG Discrepancy Flag
              </Badge>
            </div>
            <span className="text-xs text-slate-400">
              Matched against Sept 12 memory
            </span>
          </div>

          <HistoricalContextCard
            item={reportData.contradictions[0]}
            onOpenMeeting={() => onNavigate('history')}
          />
        </div>
      )}

      {/* SECTION: DECISIONS MADE */}
      <div className="space-y-4">
        <h2 className="text-lg font-bold text-white font-display">
          Agreed Architectural & Product Decisions
        </h2>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {reportData.decisions.map((dec, i) => (
            <div
              key={i}
              className="p-5 rounded-2xl glass-panel border border-indigo-500/25 space-y-2"
            >
              <Badge variant="indigo" dot size="xs">
                DECISION
              </Badge>
              <h4 className="text-sm font-bold text-white leading-snug">
                {dec.decision}
              </h4>
              <p className="text-xs text-slate-300">
                {dec.context}
              </p>
              <div className="text-[11px] text-slate-500 italic pt-2 border-t border-white/5 font-mono">
                {dec.evidence}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* SECTION: CUSTOMER REQUIREMENTS & CONCERNS */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
        <div className="p-6 rounded-2xl glass-panel border border-white/8 space-y-3">
          <h3 className="text-sm font-bold text-white uppercase tracking-wider font-mono">
            Client Requirements (FinEdge)
          </h3>
          <div className="space-y-2.5">
            {reportData.customerRequirements.map((req, i) => (
              <div key={i} className="flex items-start gap-2 text-xs text-slate-300">
                <CheckCircle2 className="w-4 h-4 text-primary-soft shrink-0 mt-0.5" />
                <div>
                  <span className="text-white font-medium">{req.requirement}</span>
                  <span className="text-slate-500 block text-[11px] font-mono">— {req.customer}</span>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="p-6 rounded-2xl glass-panel border border-amber-500/20 space-y-3">
          <h3 className="text-sm font-bold text-white uppercase tracking-wider font-mono">
            Client Concerns & Risk Exposure
          </h3>
          <div className="space-y-2.5">
            {reportData.customerConcerns.map((c, i) => (
              <div key={i} className="flex items-start gap-2 text-xs text-slate-300">
                <AlertTriangle className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
                <div>
                  <span className="text-white font-medium">{c.concern}</span>
                  <span className="text-amber-400/80 block text-[11px] font-mono">Urgency: {c.level}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* SECTION: UNRESOLVED ITEMS */}
      {reportData.unresolved.length > 0 && (
        <div className="p-5 rounded-2xl bg-rose-500/[0.04] border border-rose-500/30 space-y-3">
          <div className="flex items-center gap-2">
            <Badge variant="rose" dot size="xs">
              UNRESOLVED • NEEDS CLARIFICATION
            </Badge>
            <span className="text-xs text-rose-300 font-mono">
              Missing owner or explicit deadline
            </span>
          </div>
          {reportData.unresolved.map((u, i) => (
            <div key={i} className="text-xs space-y-1">
              <h4 className="font-bold text-white text-sm">{u.task}</h4>
              <p className="text-slate-300">{u.reason}</p>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default ReportPage;
